# Loading the Spikes
This notebook shows all the different ways how you can load spikes from the recording and what gives some ideas how to build analysis on the spiketrain dataframe.

In [33]:
from importlib import reload  
import panel as pn
import numpy as np
import Overview
import polars as pl
import stimulus_spikes
import plotly.graph_objs as go
import matplotlib.pyplot as plt
import pandas as pd
import spiketrains
import stimulus_trace

In [2]:
recording = Overview.Recording.load(r"D:\Zebrafish_14_11_23\ks_sorted\overview")

The most straightforward and most explicit way to load the spikes is to use the "get_spikes_triggered" function.
```python
def get_spikes_triggered(
            self,
            stimuli,
            cells,
            time="seconds",
            waveforms=False,
            pandas=True,
            stimulus_df="stimulus_df",
            cell_df="spikes_df",
    )
```
The stimuli and cells parameter can be provided as list of lists:
Lets look at some examples to make the idea clear.

In [4]:
# Load one stimulus and one cell
recording.get_spikes_triggered([[0]], [[0]])

cell_index      times  times_relative  trigger  repeat  times_triggered  \
0              0    9.63615         0.04295        0       0          0.04295   
1              0    9.64720         0.05400        0       0          0.05400   
2              0    9.65725         0.06405        0       0          0.06405   
3              0    9.69115         0.09795        0       0          0.09795   
4              0    9.77335         0.18015        0       0          0.18015   
...          ...        ...             ...      ...     ...              ...   
5414           0  249.66250       240.06930        5       9         23.96535   
5415           0  249.66310       240.06990        5       9         23.96595   
5416           0  249.67480       240.08160        5       9         23.97765   
5417           0  249.68985       240.09665        5       9         23.99270   
5418           0  249.69745       240.10425        5       9         24.00030   

      stimulus_index  
0                  0  
1                  0  
2                  0  
3                  0  
4                  0  
...              ...  
5414               0  
5415               0  
5416               0  
5417               0  
5418               0  

[5419 rows x 7 columns]

In [5]:
# Load one stimulus and two cells:
recording.get_spikes_triggered([[0]], [[0, 1]])

cell_index      times  times_relative  trigger  repeat  \
0               0    9.63615         0.04295        0       0   
1               0    9.64720         0.05400        0       0   
2               0    9.65725         0.06405        0       0   
3               0    9.69115         0.09795        0       0   
4               0    9.77335         0.18015        0       0   
...           ...        ...             ...      ...     ...   
10471           1  249.47495       239.88175        5       9   
10472           1  249.51690       239.92370        5       9   
10473           1  249.55105       239.95785        5       9   
10474           1  249.58790       239.99470        5       9   
10475           1  249.69000       240.09680        5       9   

       times_triggered  stimulus_index  
0              0.04295               0  
1              0.05400               0  
2              0.06405               0  
3              0.09795               0  
4              0.18015               0  
...                ...             ...  
10471         23.77780               0  
10472         23.81975               0  
10473         23.85390               0  
10474         23.89075               0  
10475         23.99285               0  

[10476 rows x 7 columns]

In [6]:
# Load two stimuli and one cell:
recording.get_spikes_triggered([[0], [1]], [[0]])

cell_index      times  times_relative  trigger  repeat  times_triggered  \
0              0    9.63615         0.04295        0       0          0.04295   
1              0    9.64720         0.05400        0       0          0.05400   
2              0    9.65725         0.06405        0       0          0.06405   
3              0    9.69115         0.09795        0       0          0.09795   
4              0    9.77335         0.18015        0       0          0.18015   
...          ...        ...             ...      ...     ...              ...   
8599           0  443.68820       145.25910        1       3         36.13455   
8600           0  443.70100       145.27190        1       3         36.14735   
8601           0  443.83465       145.40555        1       3         36.28100   
8602           0  443.85320       145.42410        1       3         36.29955   
8603           0  443.87170       145.44260        1       3         36.31805   

      stimulus_index  
0                  0  
1                  0  
2                  0  
3                  0  
4                  0  
...              ...  
8599               1  
8600               1  
8601               1  
8602               1  
8603               1  

[8604 rows x 7 columns]

In [9]:
# Load two stimuli and two cells:
recording.get_spikes_triggered([[0], [1]], [[0, 1], [0, 1]])

cell_index      times  times_relative  trigger  repeat  \
0               0    9.63615         0.04295        0       0   
1               0    9.64720         0.05400        0       0   
2               0    9.65725         0.06405        0       0   
3               0    9.69115         0.09795        0       0   
4               0    9.77335         0.18015        0       0   
...           ...        ...             ...      ...     ...   
16733           1  443.80685       145.37775        1       3   
16734           1  443.82615       145.39705        1       3   
16735           1  443.83985       145.41075        1       3   
16736           1  443.86275       145.43365        1       3   
16737           1  443.90905       145.47995        1       3   

       times_triggered  stimulus_index  
0              0.04295               0  
1              0.05400               0  
2              0.06405               0  
3              0.09795               0  
4              0.18015               0  
...                ...             ...  
16733         36.25320               1  
16734         36.27250               1  
16735         36.28620               1  
16736         36.30910               1  
16737         36.35540               1  

[16738 rows x 7 columns]

In [10]:
# Load two stimuli and two different cells for each stimulus:
recording.get_spikes_triggered([[0], [1]], [[0], [1]])

cell_index      times  times_relative  trigger  repeat  times_triggered  \
0              0    9.63615         0.04295        0       0          0.04295   
1              0    9.64720         0.05400        0       0          0.05400   
2              0    9.65725         0.06405        0       0          0.06405   
3              0    9.69115         0.09795        0       0          0.09795   
4              0    9.77335         0.18015        0       0          0.18015   
...          ...        ...             ...      ...     ...              ...   
8491           1  443.80685       145.37775        1       3         36.25320   
8492           1  443.82615       145.39705        1       3         36.27250   
8493           1  443.83985       145.41075        1       3         36.28620   
8494           1  443.86275       145.43365        1       3         36.30910   
8495           1  443.90905       145.47995        1       3         36.35540   

      stimulus_index  
0                  0  
1                  0  
2                  0  
3                  0  
4                  0  
...              ...  
8491               1  
8492               1  
8493               1  
8494               1  
8495               1  

[8496 rows x 7 columns]

In [8]:
# Load two stimuli and all cells:
recording.get_spikes_triggered([[0], [1]], [["all"]])

cell_index      times  times_relative  trigger  repeat  \
0                 0    9.63615         0.04295        0       0   
1                 0    9.64720         0.05400        0       0   
2                 0    9.65725         0.06405        0       0   
3                 0    9.69115         0.09795        0       0   
4                 0    9.77335         0.18015        0       0   
...             ...        ...             ...      ...     ...   
1265687         307  443.31550       144.88640        1       3   
1265688         307  443.74540       145.31630        1       3   
1265689         307  443.85550       145.42640        1       3   
1265690         307  443.88190       145.45280        1       3   
1265691         307  443.89640       145.46730        1       3   

         times_triggered  stimulus_index  
0                0.04295               0  
1                0.05400               0  
2                0.06405               0  
3                0.09795               0  
4                0.18015               0  
...                  ...             ...  
1265687         35.76185               1  
1265688         36.19175               1  
1265689         36.30185               1  
1265690         36.32825               1  
1265691         36.34275               1  

[1265692 rows x 7 columns]

In [ ]:
# Load all stimuli and all cells (not run here)
recording.get_spikes_triggered([["all"]], [["all"]])

## Load as numpy:
Spikes can be loaded directly as numpy arrays. In this case, you should only load a single stimulus at a time.

In [3]:
# Load a single cell
recording.get_spikes_as_numpy([0], [0])

(array([array([4.2950000e-02, 5.4000000e-02, 6.4050000e-02, ..., 2.4008160e+02,
               2.4009665e+02, 2.4010425e+02])                                  ],
       dtype=object),
 array([0], dtype=object))

In [5]:
# Load multiple cells
recording.get_spikes_as_numpy([0], [0, 1, 2])

(array([array([4.2950000e-02, 5.4000000e-02, 6.4050000e-02, ..., 2.4008160e+02,
               2.4009665e+02, 2.4010425e+02])                                  ,
        array([1.0045000e-01, 1.6760000e-01, 1.8080000e-01, ..., 2.3995785e+02,
               2.3999470e+02, 2.4009680e+02])                                  ,
        array([2.8550000e-02, 4.1800000e-02, 6.8900000e-02, ..., 2.3989640e+02,
               2.3995870e+02, 2.4003835e+02])                                  ],
       dtype=object),
 array([0, 1, 2], dtype=object))

# Loading using dataframes:
This is the most powerful and practical way to load the spikes and organize the data for analysis.
Lets say for example, we want to analyse one type of stimulus:

In [6]:
# Create a new datraframe
recording.dataframes["fff_analysis"] = recording.spikes_df.query("stimulus_name=='FFF'")

Lets say we want to only consider cells with at least 20 spikes:

In [8]:
recording.dataframes["fff_analysis"] = recording.dataframes["fff_analysis"].loc[recording.dataframes["fff_analysis"]["nr_of_spikes"]>20]

Lets load the data:

In [11]:
spikes_df = recording.get_spikes_df("fff_analysis")

Lets double check if it loaded the correct stimuli (just to make the point)

In [12]:
np.unique(spikes_df["stimulus_index"])

array([ 0,  5, 17, 19, 22, 25])

In [13]:
recording.stimulus_df

stimulus_name   begin_fr     end_fr  \
12                          FFF     191864    4994176   
13                        Chirp    5968582    8878569   
14               Contrast_Steps   10504361   17707863   
15                  Moving_Bars   22171457   32839515   
16  BW_Noise_shuffle_4px_40mins   37565472  133563677   
17                          FFF  137207884  142010213   
18                     Chirp610  142247162  145157153   
19                     Chirp560  146936893  149847364   
20                     Chirp530  150752489  153662938   
21                     Chirp460  154537534  157447978   
22                     Chirp413  163000893  165911342   
23                     Chirp365  166294901  169205410   
24                        Chirp  169536596  172447035   
25                        Chirp  175197314  178107284   
26                     FF_Noise  179404996  189404835   
27                  Moving_Bars  192854755  203522060   
28          G_Noise_shuffle_4px  206255082  302253615   
29                          FFF  304545052  309267327   
30          B_Noise_shuffle_4px  316584609  412582195   
31                          FFF  413275796  418078126   
32                        Chirp  418335560  421245546   
33                        Chirp  421646373  424556329   
34                          FFF  425205567  430007892   
35               Contrast_Steps  430391185  437594675   
36                        Chirp  438607791  441517756   
37                          FFF  442532474  447334795   

                                  trigger_fr_relative  \
12  [0, 80027, 160066, 240105, 320143, 400182, 480...   
13  [0, 60231, 727502, 787739, 1455002, 1515227, 2...   
14  [0, 80048, 160086, 240125, 320163, 400202, 480...   
15  [0, 336, 682, 994, 1328, 1657, 1984, 2318, 266...   
16  [0, 997, 1997, 2996, 3997, 4995, 5995, 6996, 7...   
17  [0, 80042, 160080, 240119, 320158, 400197, 480...   
18  [0, 60237, 727506, 787745, 1455012, 1515234, 2...   
19  [0, 60194, 727626, 787822, 1455249, 1515431, 2...   
20  [0, 60197, 727624, 787805, 1455232, 1515413, 2...   
21  [0, 60191, 727619, 787799, 1455227, 1515408, 2...   
22  [0, 60196, 727624, 787805, 1455232, 1515413, 2...   
23  [0, 60195, 727624, 787824, 1455252, 1515452, 2...   
24  [0, 60188, 727614, 787797, 1455223, 1515405, 2...   
25  [0, 60239, 727505, 787728, 1454993, 1515216, 2...   
26  [0, 999, 1999, 2999, 3999, 4999, 5999, 6999, 7...   
27  [0, 316, 610, 992, 1323, 1656, 1990, 2321, 266...   
28  [0, 992, 1991, 2991, 3990, 4990, 5990, 6989, 7...   
29  [0, 80029, 160068, 240107, 320145, 400184, 480...   
30  [0, 412, 1398, 2396, 3395, 4396, 5396, 6395, 7...   
31  [0, 80042, 160081, 240119, 320158, 400197, 480...   
32  [0, 60231, 727501, 787739, 1455005, 1515228, 2...   
33  [0, 60225, 727490, 787713, 1454979, 1515202, 2...   
34  [0, 80040, 160079, 240117, 320156, 400195, 480...   
35  [0, 80042, 160080, 240118, 320157, 400196, 480...   
36  [0, 60235, 727500, 787724, 1454988, 1515212, 2...   
37  [0, 80035, 160074, 240113, 320151, 400190, 480...   

                                          trigger_int  stimulus_index  \
12  [80027, 80039, 80039, 80038, 80039, 80039, 800...               0   
13  [60231, 667271, 60237, 667263, 60225, 667264, ...               1   
14  [80048, 80038, 80039, 80038, 80039, 80039, 800...               2   
15  [336, 346, 312, 334, 329, 327, 334, 350, 330, ...               3   
16  [997, 1000, 999, 1001, 998, 1000, 1001, 1001, ...               4   
17  [80042, 80038, 80039, 80039, 80039, 80039, 800...               5   
18  [60237, 667269, 60239, 667267, 60222, 667266, ...               6   
19  [60194, 667432, 60196, 667427, 60182, 667426, ...               7   
20  [60197, 667427, 60181, 667427, 60181, 667427, ...               8   
21  [60191, 667428, 60180, 667428, 60181, 667427, ...               9   
22  [60196, 667428, 60181, 667427, 60181, 667427, ...              10   
23  [60195, 667429, 60200, 667428, 60200, 667428, ...         

Looking good! </br>
Equally powerfull is to create a new stimulus dataframe. For example, lets say we are interested in what happens every 20 seconds during a stimulus presentation:

In [16]:
begin_frame = recording.stimulus_df["begin_fr"].to_numpy()[0]
begin_frame

191864

In [18]:
end_frame = recording.stimulus_df["end_fr"].to_numpy()[0]
end_frame

4994176

we can create a new stimulus dataframe and change the trigger arrangement:

In [43]:
recording.dataframes["fff_stimulus"] = recording.stimulus_df.query("stimulus_index==0").copy().reset_index()
recording.dataframes["fff_stimulus"]

index stimulus_name   begin_fr     end_fr  \
0     12           FFF     191864    4994176   
1     17           FFF  137207884  142010213   
2     29           FFF  304545052  309267327   
3     31           FFF  413275796  418078126   
4     34           FFF  425205567  430007892   
5     37           FFF  442532474  447334795   

                                 trigger_fr_relative  \
0  [0, 80027, 160066, 240105, 320143, 400182, 480...   
1  [0, 80042, 160080, 240119, 320158, 400197, 480...   
2  [0, 80029, 160068, 240107, 320145, 400184, 480...   
3  [0, 80042, 160081, 240119, 320158, 400197, 480...   
4  [0, 80040, 160079, 240117, 320156, 400195, 480...   
5  [0, 80035, 160074, 240113, 320151, 400190, 480...   

                                         trigger_int  stimulus_index  \
0  [80027, 80039, 80039, 80038, 80039, 80039, 800...               0   
1  [80042, 80038, 80039, 80039, 80039, 80039, 800...               5   
2  [80029, 80039, 80039, 80038, 80039, 80039, 800...              17   
3  [80042, 80039, 80038, 80039, 80039, 80039, 800...              19   
4  [80040, 80039, 80038, 80039, 80039, 80039, 800...              22   
5  [80035, 80039, 80039, 80038, 80039, 80039, 800...              25   

  stimulus_repeat_logic stimulus_repeat_sublogic sampling_freq  \
0                     6                        2       20000.0   
1                     6                        2       20000.0   
2                     6                        2       20000.0   
3                     6                        2       20000.0   
4                     6                        2       20000.0   
5                     6                        2       20000.0   

            recording                                       trigger_ends  \
0  zebrafish_14_11_23  [80027, 160065, 240104, 320143, 400181, 480220...   
1  zebrafish_14_11_23  [80038, 160080, 240118, 320157, 400196, 480235...   
2  zebrafish_14_11_23  [80029, 160067, 240106, 320145, 400184, 480222...   
3  zebrafish_14_11_23  [80038, 160081, 240119, 320157, 400196, 480235...   
4  zebrafish_14_11_23  [80038, 160078, 240117, 320156, 400194, 480234...   
5  zebrafish_14_11_23  [80035, 160073, 240112, 320151, 400189, 480228...   

  nr_repeats  
0         10  
1         10  
2          9  
3         10  
4         10  
5         10

In [39]:
#Create new triggers:
store = np.empty(1, dtype=object)
triggers_new = np.arange(begin_frame, end_frame+recording.sampling_freq*20, recording.sampling_freq*20)-begin_frame
triggers_new

array([      0,  400000,  800000, 1200000, 1600000, 2000000, 2400000,
       2800000, 3200000, 3600000, 4000000, 4400000, 4800000, 5200000])

In [40]:
# Add back to the dataframe:
store[0] = triggers_new
recording.dataframes["fff_stimulus"]["trigger_fr_relative"] = store
store[0] = np.diff(triggers_new)
recording.dataframes["fff_stimulus"]["trigger_int"] = store
recording.dataframes["fff_stimulus"]["stimulus_repeat_logic"] = 1
recording.dataframes["fff_stimulus"]["stimulus_repeat_sublogic"] = 2
recording.dataframes["fff_stimulus"] = stimulus_trace.find_ends(recording.dataframes["fff_stimulus"])
recording.dataframes["fff_stimulus"] = stimulus_trace.get_nr_repeats(recording.dataframes["fff_stimulus"])

In [41]:
recording.dataframes["fff_stimulus"]

index stimulus_name begin_fr   end_fr  \
0     12           FFF   191864  4994176   

                                 trigger_fr_relative  \
0  [0, 400000, 800000, 1200000, 1600000, 2000000,...   

                                         trigger_int  stimulus_index  \
0  [400000, 400000, 400000, 400000, 400000, 40000...               0   

   stimulus_repeat_logic  stimulus_repeat_sublogic sampling_freq  \
0                      1                         2       20000.0   

            recording                                       trigger_ends  \
0  zebrafish_14_11_23  [400000, 800000, 1200000, 1600000, 2000000, 24...   

   nr_repeats  
0          13

In [44]:
spikes_df = recording.get_spikes_df(stimulus_df="fff_stimulus")

IndexError: index 0 is out of bounds for axis 0 with size 0